# git install

- name: install the latest version of Git redhat
  yum: name=git state=latest
  when: ansible_os_family == "RedHat"

- name: install the laster version of Git debain
  apt: name=git state=present
  when: ansible_os_family == "Debian"
