# task for creating aws instances, create hosts group

- name: Provision a set of instances
  ec2:
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    image: "{{ image }}"
    wait: true
    exact_count: "{{ count }}"
    count_tag:
      Name: "{{ tag_name }}"
    instance_tags:
      Name: "{{ tag_name }}"
  register: ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=ec2hosts
  with_items: ec2.instances

- name: Wait for the instances to boot by checking the ssh port, check by dns
  wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
    
- name: Wait for the instances to boot by checking the ssh port, check by ip
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
